OHDSI/Vocabulary-v5.0

- README.md
Now that the download center is up and running, add a link to it in the README.
> README.md: Include link to ATHENA

- LOINC/load_stage.sql
@hardhouse and @dimshitc, please, review the updated LOINC load stage script and merge it (if everything is fine).
> LOINC Updated Load Stage

- PPI/load_stage.sql
- PPI/readme.md
@dimshitc and @hardhouse, please, review a newly created folder for PPI Vocabulary, which contains a load stage script and a readme file
> a new folder for PPI Vocabulary

- SNOMED/load_stage.sql
Repair peaks and domains for COVID (and a little bit for CAP)
> SNOMED fix

- Nebraska Lexicon/load_stage.sql
Hotfix for manual assignment of Domains and fix for dates
> Nebraska Update

- SNOMED/load_stage.sql
https://odysseusdataservices.atlassian.net/browse/AVOF-2428
> SNOMED load_stage change

- CPT4/load_stage.sql
Changes:
1. New concepts (COVID19 + missing ones) -- manual hierarchical change
2. The logic for the domain distribution (a new source table is required) -- improved
3. Ressurection of Deprecated concepts
4. Concept name formulation
5. New synonyms with source concept class inside the names
6. Content of concept_relationship_manual (minor fixes)
> domain and covid-19 concept hierarchy fixes

- CPT4/load_stage.sql
Changes:
1. New concepts (COVID19 + missing ones)
2. The logic for the domain distribution (a new source table is required)
3. Ressurection of Deprecated concepts 
4. Concept name formulation
5. New synonyms with source concept class inside the names
6. Content of concept_relationship_manual (minor fixes)
> CPT4: COVID-19 related changes

- NCCD/README.md
- NCCD/create_source_tables.sql
- NCCD/load_stage.sql
- NCCD/manual_changes.sql
need to add a link in the readme for a place where the source table can be placed.
> NCCD new vocabulary

- working/input_QA_integratable_W.sql
- working/manual_checks_after_generic.sql
1) Please add to manual changes after generic
I used these checks for the Drug vocabulary (Gemscript), but they can be applied to any vocabulary.
Please add what you have.
Note, if you have checks specific for some group vocabularies (i.e. RxNorm Extension sources, ICDs), please create corresponding file for them.
2) input drug QA update. added 3 checks to warnings. should be pretty straightforward
> input drug QA update, + manual checks after generic

- CPT4/load_stage.sql
- CPT4/readme.md
Moved manual work after domain definition by code patterns but before domain definition by mappings
> Cpt4 covid vacc

- RxNorm_E/mini_load_stage.sql
- RxNorm_E/readme.md
- RxNorm_E/readme_for_manual_tables.md
Manually added concepts with their synonyms and relationships are added by mini_load_stage (tables are populated from CSV files)
> RxNorm_Extension initial commit with manual tables populated

- HCPCS/ProcedureDrug.sql
Still needs to be reworked: currently works worse than manually adding mappings to concept_relationship_manual
> Fixed the ProcedureDrug script a little

- working/manual_changes/2021/2021-03-29.sql
New vocabulary: OncoKB
New relationship: Has Variant
> New Vocab and new relationship

- working/manual_changes/2021/2021-07-23.sql
Remove duplicates from provider domain [AVOF-3219, AVOF-3005]
> New manual file

- ICD10CM/manual_work/create_manual_table.sql
- ICD10CM/manual_work/crm_changes.sql
- ICD10CM/manual_work/manual_mapping_qa.sql
- ICD10CM/manual_work/mapping_refresh.sql
- ICD10CM/manual_work/readme.md
- ICD10CM/readme.md
This algorithm was created based on ICD10 documentation. In my opinion, we should have this number of 'almost the same algorithm' to make updates easier and clearer. As for me, it is better to have it all in one place than switch from one link to another to follow one solid algorithm.
> Icd10cm documentation

- ICD10CN/load_stage.sql
- ICD10CN/readme.md
This algorithm was created based on ICD10 documentation. However, Chinese vocabulary doesn't have any manual part. So, manual work is omitted
> Icd10cn documentation

- working/manual_changes/2022/2022-05-04.sql
> https://github.com/OHDSI/Vocabulary-v5.0/issues/618

- OMOP Invest Drug/load_stage.sql
Approval_id stands for the UNII code, which is widely used, so it's used as an OMOP concept_code
> use FDA UNII code as concept_code

- .github/ISSUE_TEMPLATE/faulty-content.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/new-vocabulary-implementation-request.md
- CVX/readme.md
- HCPCS/load_stage.sql
- HCPCS/manual work/hcpcs_refresh.sql
- HCPCS/manual work/readme.md
- SNOMED/load_stage.sql
- working/manual_checks_after_generic.sql
1) Directory 'manual work' created with hcpcs_refresh.sql and readme.md inside
2) Domain assignment in load_stage.sql changed (p.4 and p.19)
3) readme.md updated
> Hcpcs refresh 2022

- NAACCR/load_stage.sql
- NAACCR/manual work/manual_work_01-Sep-22.sql
NAACCR mapping ingestion per [request](https://github.com/OHDSI/Vocabulary-v5.0/issues/668).
> Naaccr sep2022 patch

- Cancer Modifier/load_stage.sql
- Cancer Modifier/manual_work/patch_2022_08_31.sql
The Cancer Modifier Sep2022 patch adresses 2 issues 
- https://github.com/OHDSI/Vocabulary-v5.0/issues/645
- https://github.com/OHDSI/Vocabulary-v5.0/issues/664
This Fix rename Nodes concepts, new code was added to improve cancer regisries ETL
> Cancer mod aug2022 patch

- working/manual_changes/2022/2022-09-20.sql
> feat: add a Note Domain function

- CIViC/load_stage.sql
CIViC is updated as new synthetic Language for Genetic nomenclature was added.
> CIViC update of language_concept_id

- SNOMED/load_stage.sql
- SNOMED/manual_work/snomed_refresh.sql
A new domain for languages has been assigned
Process of working with manual tables has been rearranged (invalid_reason flag is included now)
> SNOMED - Monkeypox release

- LOINC/load_stage.sql
- LOINC/manual_work/loinc_refresh.sql
- LOINC/manual_work/project_specific_manual_checks_after_generic.sql
- working/manual_changes/2022/2022-09-19.sql
Domain Note + fixing estrogen measurements hierarchy
> Loinc refresh v2.73

- working/MapDrugVocab.sql
The previous version of MapDrugVocab failed on huge datasets (~1 million rows). The creation of map_drug has been refactored for better performance by @hardhouse
> MapDrugVocab refactoring

- working/input_QA_integratable_E.sql
- working/input_QA_integratable_W.sql
- working/input_tables_DDL.sql
Added DDL
Moved drugs with no ingredients from W to E
> input tables DDL and QA

- MeSH/load_stage.sql
During this release, we add missing MeSh codes (more than 330000 concepts) and change the logic of domain assignment
> Mesh 2023 fix: missing codes and domain assignment

- NAACCR/manual work/checks.sql
- NAACCR/manual work/manual_work_08-Feb-23.sql
The update provide the community-based mappings: NAACCR Values to Cancer Modifier.
Only a minor portion of provided tarrgets are curated and repalced with more suitable/appropriate ones (Generic lymphonodal spread rwplaced with Regional spread to lymph node as they are semantical children of Regionl lymph node Variable.
> Naaccr manual update feb2023

- RxNorm/FillDrugStrengthStage.sql
- working/manual_changes/2023/2023-12-26.sql
Concept_ids of the units must be changed when new concepts are introduced in devv5
> Two new units introduced by RxNorm - February 2024 release

- NDC_SPL/load_stage.sql
- NDC_SPL/manual_work/NDC_SPL_refresh.sql
- NDC_SPL/manual_work/readme.md
Manual file processing changed to new standard; concept_manual prioritised over load_stage
> NDC February 2024

- working/packages/vocabulary_pack/BuildRxE.sql
Solution to undeterminate query problem, when executed on the same source.
> Fix AVOC-3852 undetermined query

- .github/ISSUE_TEMPLATE/add-content.md
I worked with the issue template some days ago and found some spelling mistakes and things that were not clear to me immediately. So I fixed the spelling errors and tried to make it more explicit. Maybe you will find this contribution helpful.
> Improve GitHub issue template for "add-content.md"

- OMOP Extension/load_stage.sql
Follow up after the Snomed release in February 2024
> Add Disorder as available concept_class_id for OMOP Extension

- working/manual_changes/2024/2024-02-29.sql
Update of content to complement OMOP Genomic February 2024 release
> Add new concept_classes for OMOP Genomic; modify vocabulary_name

- working/local_environment/DevV5_constraints_DDL.sql
- working/local_environment/DevV5_tables_DDL.sql
- working/local_environment/GenericUpdate_LE.sql
- working/local_environment/README.md
The Instruction and scripts to prepare a local environment for Vocabulary Development process
> Prepare a local environment for Vocabulary Development process

- working/manual_checks_after_generic_update.sql
Transferred from Bitbucket by Tetiana O
> Update concept changed their synonyms to detect language change

- working/packages/vocabulary_pack/CheckVocabularyUpdate.sql
Fix CheckVocabularyUpdate parsing for HCPCS
> Fix CheckVocabularyUpdate parsing for HCPCS

- working/packages/vocabulary_download/get_ndc_spl.sql
- working/packages/vocabulary_download/run_curl.sql
- create run_curl() function to load source files using curl in get_ndc_spl() instead of run_wget()
> Fix NDCSPL autodownload:

- EDI/create_source_tables.sql
- EDI/load_stage.sql
- EDI/readme.md
> EDI update

- working/manual_changes/2024/2024-08-29.sql
https://forums.ohdsi.org/t/units-of-measure-to-add/11260/31
> Two new units added

- ATC/create_source_tables.sql
- working/packages/load_input_tables/load_input_tables.sql
- working/packages/vocabulary_download/UpdateAllVocabularies.sql
- working/packages/vocabulary_download/get_atc.sql
- working/packages/vocabulary_download/py_load_atc.sql
- working/packages/vocabulary_pack/CheckVocabularyUpdate.sql
- py_load_atc(): scraper to get ATC source data
- get_atc(): function to start load input tables process for ATC
- load_input_tables(): add inserting data into atc_codes table from ATC scraper
- CheckVocabularyUpdate(): add part to check ATC source data
- Add DDL script for atc_codes table
> Add and modify functions for automatic downloading ATC sources

- SNOMED/create_source_tables.sql
- working/packages/load_input_tables/load_input_tables.sql
- working/packages/sources_archive/CreateCustomSnomedSource.sql
- working/packages/vocabulary_download/UpdateAllVocabularies.sql
- working/packages/vocabulary_download/get_snomed.sql
- working/packages/vocabulary_pack/CheckVocabularyUpdate.sql
- Split SNOMED source tables into 4 modules for custom merge
- Add a function to create _merged source tables
> Snomed custom sources

- working/packages/admin_pack/LogManualChanges.sql
Clear logs for concept_manual and conept_relationship_manual tables when changes are rolled back in dev schema
> Fix log manual changes

- working/metadata/readme.md
> Fix readme

- MedDRA/manual_work/meddra_refresh.sql
- MedDRA/manual_work/meddra_specific_checks.sql
Small corrections in meddra_refresh and additional checks of hierarchy between MedDRA and SNOMED
> Meddra june 2025
